FROM openjdk:8-jre-alpine
EXPOSE 8080
WORKDIR /app
COPY target/challenge-birras-santander-login-0.0.1-SNAPSHOT.jar .
ENTRYPOINT [ "java", "-jar", "challenge-birras-santander-login-0.0.1-SNAPSHOT.jar" ]