
version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Santander123
      TZ: America/Argentina/Buenos_Aires

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8085:80'
    environment:
      PMA_HOST: db

  #service 3: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: challenge-birras-santander-login               #name of the image after dockerfile executes
    container_name: challenge-birras-santander-login  #name of the container created from docker image
    build:
      context: ./challenge-birras-santander-login                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://appsDB:3306/santander_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Santander123

  #service 4: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: challenge-birras-santander-meet-up                #name of the image after dockerfile executes
    container_name: challenge-birras-santander-meet-up  #name of the container created from docker image
    build:
      context: ./challenge-birras-santander-meet-up                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8081:8081"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://appsDB:3306/santander_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Santander123
