
version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Santander123
      TZ: America/Argentina/Buenos_Aires

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    environment:
      - "TZ=America/Argentina/Buenos_Aires"
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61616:61616"
      - "8161:8161"

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8085:80'
    environment:
      PMA_HOST: db

  login-service:
    image: challenge-birras-santander-login
    container_name: challenge-birras-santander-login
    build:
      context: ./challenge-birras-santander-login
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

    depends_on:
      - db
    environment:
      TZ: America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_URL: jdbc:mysql://appsDB:3306/santander_db?createDatabaseIfNotExist=true&TZ=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Santander123


  meet-up-service:
    image: challenge-birras-santander-meet-up
    container_name: challenge-birras-santander-meet-up
    build:
      context: ./challenge-birras-santander-meet-up
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always

    depends_on:
      - db
    environment:
      TZ: America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_URL: jdbc:mysql://appsDB:3306/santander_db?createDatabaseIfNotExist=true&TZ=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Santander123
      KEY_WEATHER: 7d1046095emsh5c40257db3ecc8fp14f89bjsn370c2ada41d8
      HOST_WEATHER: community-open-weather-map.p.rapidapi.com
      URL_WEATHER: https://community-open-weather-map.p.rapidapi.com/forecast/daily?q=argentina&ar&units=metric&cnt=16
      FIXED_RATE: 600000
      AMQ_USER: admin
      AMQ_PASS: admin
      RESEND_MQ_DELAY: 1000000
      MQ_QUEUE: meetUp
      MANAGER_AMQ_URL: tcp://activemq:61616