FROM openjdk:8-jre-alpine
EXPOSE 8081
WORKDIR /app
COPY target/challenge-birras-santander-meet-up-0.0.1-SNAPSHOT.jar .
ENTRYPOINT [ "java", "-jar", "challenge-birras-santander-meet-up-0.0.1-SNAPSHOT.jar" ]